### ISSUE TITLE
No sound output?

### ISSUE THREAD

**Issue by wbb1977** [Deltafire/SCPlayer#2]
Hi

I compiled the library and scplay. I try to load via scplay <file>.cop, but no sound output. I added a few debug printf and Etracker is loaded etc. However no OUT, 0x1FF ever is generated to write into the sound chip. 

Can you confirm that everything works or I am missing something?

Best regards
Bastian

**Comment by Deltafire** [comment]
Most likely scplay isn’t receiving any callbacks from the SDL audio driver.  Check that mixerCallback is being called.

**Comment by wbb1977** [comment]
Thank you for quick reply.

I checked and mixerCallback function is called. It is called with 882 samples requested as expected. The emulation is running but somehow the OUT 0x1FF, reg and OUT 0x0FF, val are not generated. I tried several files and added some debug output, but I am lost.

**Comment by Deltafire** [comment]
Hmm.. Not sure what the problem could be.  It running fine here on OSX, what system/compiler are you using?

**Comment by wbb1977** [comment]
I am on Debian 7.9 (Amd64), gcc 4.7.2.
Ok good to know that is on my end. I added debug printf in the Z80_out function. For each file I try I get random OUT to different ports.
It looks like a bigger problem.

**Comment by Deltafire** [comment]
Maybe it’s an endian problem - check line 28 -31 of z80.h.

**Comment by wbb1977** [comment]
I checked and made sure that #LSB_FIRST is defined as I am on Little Endian. Despite, I tested both with different results but unfortunately no sound output. No problem, maybe I find out the cause in the future :)

**Comment by Deltafire** [comment]
Hopefully upgrading both SAASound and SDL has resolved whatever was causing this issue, but please re-open if it's still present.
